// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d5234e02-9c9b-4176-bd09-a14962dfb8aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bp5WkbuET",
    "aws_user_pools_web_client_id": "5v2sec89qunai0tstqn8tcg9g",
    "oauth": {},
    "aws_user_files_s3_bucket": "dashboardlogin92962e9cae16493ea6cba17767c61d4a191244-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
